replicaCount: 1

image:
  repository: curlup/jira-mattermost-webhook-bridge
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 5000

env:
  MATTERMOST_WEBHOOK_URL: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: jira-mattermost.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []