apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-mattermost-webhook-bridge
  labels:
    app: jira-mattermost-webhook-bridge
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jira-mattermost-webhook-bridge
  template:
    metadata:
      labels:
        app: jira-mattermost-webhook-bridge
    spec:
      containers:
        - name: jira-mattermost-webhook-bridge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: MATTERMOST_WEBHOOK_URL
              value: "{{ .Values.env.MATTERMOST_WEBHOOK_URL }}"
